### PR TITLE
Add Chinese Simplified translation

### PR DESCRIPTION
**Pull request by shun2wang**
Initial Chinese Simplified translation

- [ ] Maybe need to check the plural format.
- [ ] Is it possible to compile a version with this translation so that we can check the last translation.

### CODE REVIEW

**Comment by jonathon-love** [comment]
awesome. i'll see if i can put a version together for you in the next couple of days. thanks for your efforts here!

**Comment by jonathon-love** [comment]
> Maybe need to check the plural format.

yup, let me look into that.

i see you've specified a language code of `zh_CN` ... i'm wondering if just `zh` would be more appropriate.

the advantage of simply `zh` is that if someone is using a different ... dialect? ... i.e. `zh_XX` then `zh` will be a fallback for any `zh_XX` language that we don't support yet. alternatively, we just use `zh_CN`, and then other `zh_XX` users (that we don't support yet) will be provided english.

(take english itself for example, we use the `en` language code, and we have `en-AU`, `en-US`, `en-UK` ... but we just use `en` for all of these because even though we have different language codes, we almost don't notice the difference between them :P)

what's the most appropriate here do you think?

whatever we decide, the filename should match the code, i.e. `zh_CN.po`.

**Comment by shun2wang** [comment]
Thank you for pointing this out.

I think `zh_Hans` should be used as a unified language mark to indicate ’Chinese Simplified‘ (中文简体).
I refer to the language coding standard of [RFC(bcp47)](https://www.rfc-editor.org/rfc/bcp/bcp47.txt)，As you know, Chinese is divided into simplified and traditional forms,There are some differences between the two in character form and expression.the `zh` as all chinese language.
I do not recommend using the `CN` tag to distinguish the country of use ,in order to have a wider range of applications for user, but only use `Hans` to distinguish simplified and traditional Chinese(中文繁体,tag `zh_Hant`).the `cn` in the .po file from Poedit tool.
All in all, we can use `zh_Hans` and `zh_Hant`to distinguish all Chinese forms.

I will initiate a pull request in a few minutes to fix the above and other changes.

**Comment by shun2wang** [comment]
Thanks again for your efforts.

Merry Christmas Eve to you and the jamovi team！😀

**Comment by jonathon-love** [comment]
awesome. thanks for your work. most web browsers use ISO 639-1 codes, so that's what we're using too. is there an iso 639-1 equivalent of `zh-Hans`?

**Comment by shun2wang** [comment]
> is there an iso 639-1 equivalent of `zh-Hans`

I find only `zh` in [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes),and I find `zh-Hans` in [W3C](https://www.w3.org/International/articles/language-tags/),The availability of `zh-Hans`and`zh-Hant` for Chinese written in Simplified and Traditional scripts should improve consistency and accuracy,but the `zh-CN` and `zh-TW` are equivalent to them and widely used.

By the way, whether '-' is better than '_' , I have no idea.

**Comment by shun2wang** [comment]
I used English en.po file as a reference in the translation, but I find that it seems that the Japanese translation ja.po string is more. Are some strings missing ?

**Comment by jonathon-love** [comment]
> I used English en.po file as a reference in the translation, but I find that it seems that the Japanese translation ja.po string is more. Are some strings missing ?

oh yup, that could be. because english is the base language, it doesn't matter if there's entries missing from it, so we might not have realised it's not up to date.

for future reference, you're supposed to begin with the `catalog.pot` ...

let me know if you need a hand merging the `catalog.pot` into your .po file.

**Comment by jonathon-love** [comment]
taking a look [here](https://newbedev.com/language-codes-for-simplified-chinese-and-traditional-chinese) i think we either want to use `zh` or `zh_CN`.

could you go [here](https://www.jamovi.org/misc/what-values.html), and tell me what values your browser is using.

the rationale for using `zh` is that it will be the fallback for `zh_TW` ... until that translation is created. ... because `zh` is (i assume) a better fallback than `en`

**Comment by shun2wang** [comment]
> could you go here, and tell me what values your browser is using.

in Chrome:
```
"zh-CN"

["zh-CN","zh","en"]
```
in Firefox:
```
"zh-CN"

["zh-CN","zh","zh-TW","zh-HK","en-US","en"]
```
so we can use `zh-CN` as first choice?

**Comment by jonathon-love** [comment]
> so we can use zh-CN as first choice?

sure.

**Comment by shun2wang** [comment]
So far we have completed all translation and review work, please merge and make a version with it at a suitable time.

Thank you for your guidance and work!

**Comment by jonathon-love** [comment]
i've put this up on the cloud version if you want to take a look:

https://cloud.jamovi.org

obviously, you still need to PR the translations for jmv for the analyses to be translated.

cheers

**Comment by shun2wang** [comment]
Great! It already works.
Yes, translation work for jmv has started.But need to open another PR in jmv repositories, right?

**Comment by jonathon-love** [comment]
> But need to open another PR in jmv repositories, right?

yup, exactly.

**Comment by jonathon-love** [comment]
we'll also need you to fill in a CLA, as per the instructions here:

https://github.com/jamovi/jamovi/blob/current-dev/CONTRIBUTING.md

once you've done that, i'll close this PR, and get you to open a new PR ... to make it clear the submission falls under the CLA.

cheers

**Comment by shun2wang** [comment]
>we'll also need you to fill in a CLA, as per the instructions here:

Yes I have finished it.
>and get you to open a new PR

I'll do that.

thanks!

**Comment by jonathon-love** [comment]
can you open a new PR? thanks

**Pull request closed without merging**
