### PR TITLE
Added Chinese Simplified translation

### PR DESCRIPTION
**Pull request by shun2wang**

### CODE REVIEW

**Comment by jonathon-love** [comment]
thanks! have you taken a look at https://cloud.jamovi.org ?

there's an opportunity to see your own translations live, and you can also take a look at what the mengte guys have done, and see if there's any tweaks you think they should make.

cheers

**Comment by icekylin** [comment]
> https://cloud.jamovi.org ?

Yes, I've done this and found some undefined translations (it's easy to do this under non-english interfaces)

>and you can also take a look at what the mengte guys have done

Some of their colleagues have reviewed my work, but I have not seen their mengte (a business entity) work and have done some proofreading, but I have tried to notify others to review it as much as possible.I think the next time more translation in POT file are added,  if there is an update merged.

**Comment by shun2wang** [comment]
>https://cloud.jamovi.org ?

Yes, we have done this and found some undefined translations (it's easy to do this under non-english interfaces)

>and you can also take a look at what the mengte guys have done

Of course，Some of their colleagues have reviewed my work on cloud.jamovi.org, I have tried to notify others to do it as much as possible. so we will review the final translation together.
I think once more translation strings in POT file are added, maybe there is an update merged with new translation in the next time.

**Comment by shun2wang** [comment]
@jonathon-love I think it's time to merge it.

**Pull request merged**
