### PR TITLE
Sync with current state on Weblate

### PR DESCRIPTION
**Pull request by sjentsch**
The German and Norwegian translations are by me, the Slovenian translations by Matej Urban <mateju@src.gnome.org>.
Portugese got a little reformatted since I opened it in Weblate and removed a couple of double spaces.

### CODE REVIEW

**Comment by jonathon-love** [comment]
shall we make `nb_NO` into `nb`? (or `nb-no` if you think the `-no` is important).

**Comment by sjentsch** [comment]
Rather not. I am uncertain whether Weblate would still recognize the language if we change that. Why is it important?

**Comment by jonathon-love** [comment]
our implementation is based on the standard (i forget it's name), so an underscore is verboten, and damo's implementation assumes all lowercase (the standard is non case sensitive) ... so weblate should be able to handle these.

**Comment by sjentsch** [comment]
I just checked, you can rename it to "no", Weblate gets that. I don't believe it accepts "nb" (which actually denotes one of the two "dialects" we we have).

**Comment by jonathon-love** [comment]
yup. `no` sounds perfect.

**Comment by jonathon-love** [comment]
i gather you can't do separate commits for each language? no biggie, but i can then assign people names/email addresses to the commits for each language, and they'll appear in the contributors list on github.

**Comment by sjentsch** [comment]
Look at the first message with the commit for who did translate it (me for German and Norwegian) and Matej for what so far exists for Slovenian.

**Comment by jonathon-love** [comment]
sure. i can take this commit, splice it up into separate commits, etc. but ideally there's a way that weblate can do that for us? i can do it this time, but it's too much work for me to be sustainable into the future.

so if weblate can separate the commits, that will be awesome, otherwise we might just have to accept that gh won't be a good record of people's contributions ... which if that has to be the case, then so be it.

**Comment by jonathon-love** [comment]
i've committed the german and norwegian.

**Comment by jonathon-love** [comment]
are you around one evening where we can have a phone call about this?

this is great this is coming together, but i'd like to see if there's a way we can do this which is a bit tidier.

one of the problems is that i only want to merge translations which are complete ... but at present, there's no way for me to selectively do that.

**Pull request merged**
